version: '3.9'

services:
  sqlserver:
    container_name: mssql
    build:
      context: ./mssql
    environment:
      SA_PASSWORD: "mssql1Ipw"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      DATABASE: "SimpleCRM"
    ports:
      - "1433:1433"
    networks:
      - api-compose-network
      
  api:
    container_name: api
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      HOST: "sqlserver"
      PORT: 1433
      USERNAME: "sa"
      PASSWORD: "mssql1Ipw"
      DATABASE: "SimpleCRM"
      SECRET_KEY: "vCpl8LAm0q"
      EXPIRATION_TOKEN: 3600
    depends_on:
      - sqlserver
    networks:
      - api-compose-network

networks: 
  api-compose-network:
    driver: bridge