version: '3.9'

services:
  sqlserver:
    container_name: mssql
    build:
      context: ./mssql
    environment:
      SA_PASSWORD: "mssql1Ipw"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      DATABASE: "SimpleCRM"
    ports:
      - "1433:1433"
    networks:
      - api-compose-network
      
networks: 
  api-compose-network:
    driver: bridge